### ISSUE TITLE
Failed to create/init foxglove-extension template 

### ISSUE THREAD

**Issue by hardik-a62** [foxglove/create-foxglove-extension#90]
**I am trying to get hands on for foxglove custom panel extesion. I am following getting started guide [https://foxglove.dev/docs/studio/extensions/getting-started] for that.

Installed node.js, npm and yarn as per the requirement.
**
-- Nodejs version: v10.19.0
-- npm version: 6.14.4
-- yarn version: 1.22.19

**Steps To Reproduce**

Trying to create template for extension project but it failed.
`npm init foxglove-extension@latest helloworld`

**Error:**

npx: installed 142 in 14.482s
/home/clutterbot-a62/.npm/_npx/60751/lib/node_modules/create-foxglove-extension/dist/build.js:39
    const env = options.mode ?? (process.env.NODE_ENV === "production" ? "production" : "development");
                              ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/clutterbot-a62/.npm/_npx/60751/lib/node_modules/create-foxglove-extension/dist/index.js:17:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Expected Behavior**
It should create a folder with project template.

**Comment by hardik-a62** [comment]
Resolved. Need to update the nodejs to version to 14+.
